"""
AEGIS - Fixed-Time Trade Intent.

Represents an immutable trading intention generated by a strategy.

A TradeIntent does not represent an executed operation.

Instead, it represents the intention of opening a fixed-time contract
after all risk validations have been successfully completed.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from decimal import Decimal
from types import MappingProxyType
from typing import Any, Mapping
from uuid import uuid4

from .enums import FixedTimeDirection
from .exceptions import (
    InvalidDirectionError,
    InvalidPayoutError,
    InvalidStakeError,
    InvalidTradeIntentError,
)


@dataclass(frozen=True, slots=True)
class TradeIntent:
    """
    Immutable representation of a trading intention.

    A TradeIntent is produced by a strategy and consumed by the
    TradeLifecycleCoordinator after risk validation.

    It contains only business information describing the desired
    operation.
    """

    symbol: str

    direction: FixedTimeDirection

    stake: Decimal

    requested_payout: Decimal

    duration: int

    strategy_id: str

    signal_id: str

    intent_id: str = field(default_factory=lambda: str(uuid4()))

    created_at: datetime = field(
        default_factory=lambda: datetime.now(UTC)
    )

    metadata: Mapping[str, Any] = field(
        default_factory=dict
    )

    def __post_init__(self) -> None:
        """
        Validate all domain invariants.
        """

        if not self.symbol.strip():
            raise InvalidTradeIntentError(
                "Symbol cannot be empty."
            )

        if not isinstance(
            self.direction,
            FixedTimeDirection,
        ):
            raise InvalidDirectionError(
                "Invalid trade direction."
            )

        if self.stake <= Decimal("0"):
            raise InvalidStakeError(
                "Stake must be greater than zero."
            )

        if self.requested_payout <= Decimal("0"):
            raise InvalidPayoutError(
                "Requested payout must be greater than zero."
            )

        if self.duration <= 0:
            raise InvalidTradeIntentError(
                "Duration must be greater than zero."
            )

        if not self.strategy_id.strip():
            raise InvalidTradeIntentError(
                "Strategy id cannot be empty."
            )

        if not self.signal_id.strip():
            raise InvalidTradeIntentError(
                "Signal id cannot be empty."
            )

        object.__setattr__(
            self,
            "metadata",
            MappingProxyType(dict(self.metadata)),
        )

    @property
    def is_call(self) -> bool:
        """
        Returns True if this is a CALL operation.
        """
        return self.direction is FixedTimeDirection.CALL

    @property
    def is_put(self) -> bool:
        """
        Returns True if this is a PUT operation.
        """
        return self.direction is FixedTimeDirection.PUT